import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/contact";
import { roboto, ibmPlexSerif } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={`${roboto.variable} ${ibmPlexSerif.variable} h-full antialiased`}
    >
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
